// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLEi9z4pUP5Mt92FThFzSZzmtzsWPwiBQ',
    appId: '1:375222148615:web:37a8bf44d328775e4794a2',
    messagingSenderId: '375222148615',
    projectId: 'flutter-task-9-3197a',
    authDomain: 'flutter-task-9-3197a.firebaseapp.com',
    databaseURL: 'https://flutter-task-9-3197a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-task-9-3197a.firebasestorage.app',
    measurementId: 'G-9JPW8LD51F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDFhcd3iJQ-xbo-z0GnETVoGotAWrLdWk',
    appId: '1:375222148615:android:873ea52cbb81f76e4794a2',
    messagingSenderId: '375222148615',
    projectId: 'flutter-task-9-3197a',
    databaseURL: 'https://flutter-task-9-3197a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-task-9-3197a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRrls3xFJisTxZPtsVeqax58TUvocuJFo',
    appId: '1:375222148615:ios:cb616bc85271a87a4794a2',
    messagingSenderId: '375222148615',
    projectId: 'flutter-task-9-3197a',
    databaseURL: 'https://flutter-task-9-3197a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-task-9-3197a.firebasestorage.app',
    iosBundleId: 'com.example.task9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRrls3xFJisTxZPtsVeqax58TUvocuJFo',
    appId: '1:375222148615:ios:cb616bc85271a87a4794a2',
    messagingSenderId: '375222148615',
    projectId: 'flutter-task-9-3197a',
    databaseURL: 'https://flutter-task-9-3197a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-task-9-3197a.firebasestorage.app',
    iosBundleId: 'com.example.task9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLEi9z4pUP5Mt92FThFzSZzmtzsWPwiBQ',
    appId: '1:375222148615:web:04f055d7dcf1e7ef4794a2',
    messagingSenderId: '375222148615',
    projectId: 'flutter-task-9-3197a',
    authDomain: 'flutter-task-9-3197a.firebaseapp.com',
    databaseURL: 'https://flutter-task-9-3197a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-task-9-3197a.firebasestorage.app',
    measurementId: 'G-TPZ1Y2QFDS',
  );
}
